#!/bin/sh

case "$1" in
    start )
        if [ -e /dev/mmcblk1 ]
        then
            modprobe g_mass_storage file=/dev/mmcblk1p1,/dev/mmcblk1p2 luns=2 ro=1,0 stall=0,0,0 removable=1,1 iSerialNumber=3000111 iProduct=zhdgnss iManufacturer=zhd_survey
#modprobe g_mass_storage file=/mnt/static/static.img,/mnt/static/driver.img,/mnt/dynamic/update.img luns=3 ro=1,1,0 stall=0,0,0 removable=1,1,1 iSerialNumber=30001111 iProduct=vnet iManufacturer=ZHD
        fi
    ;;
    stop )
        lsmod | grep g_file_storage > /dev/null
        if [ "$?" == "0" ]
        then
            rmmod g_mass_storage
        fi
    ;;
esac

exit 0
