#! /bin/sh

telnetd=/sbin/telnetd

test -x "$telnetd" || exit 0

case "$1" in
  start)
    echo -n "Starting telnet daemon"
    start-stop-daemon --start --quiet --exec $telnetd
    echo "..."
    ;;
  stop)
    echo -n "Stopping telnet daemon"
    start-stop-daemon --stop --quiet --pidfile /var/run/telnetd.pidls
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/telnetd {start|stop}"
    exit 1
esac
date > /tmp/telnettime
exit 0
