#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

/bin/mount -a
# build mdev 
mount -t tmpfs mdev /dev
echo /bin/mdev > /proc/sys/kernel/hotplug
mdev -s
#needed for telnet to work properly
#/bin/mkdir /dev/pts

/bin/mount n /dev/pts -t devpts

#/bin/mkdir -p /tmp/run
#/bin/mkdir -p /tmp/lock

#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc
#/bin/mkdir -p /huan

if [ -e /dev/mmcblk0p1 ]
then
     echo "hzq mounting mmc1 "
    /bin/mount    /dev/mmcblk0p1 /mnt 
    modprobe g_mass_storage file=/dev/mmcblk0p1    
fi

# mount 
#
#	Source defaults.
#
#. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
#trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
exec /etc/init.d/rc S

#
#	For compatibility, run the files in /etc/rc.boot too.
#
#[ -d /etc/rc.boot ] && run-parts /etc/rc.boot

#
#	Finish setup if needed. The comment above about
#	/sbin/unconfigured.sh applies here as well!
#
#if [ -x /sbin/setup.sh ]
#then
#  /sbin/setup.sh
#fi

